minimumReleaseAge: 1440

packages:
  - artifacts/*
  - lib/*

catalog:
  '@types/node': ^25.3.3
  '@types/pg': ^8.20.0
  '@types/cookie-parser': ^1.4.10
  '@types/cors': ^2.8.19
  '@types/express': ^5.0.6
  'drizzle-orm': ^0.45.2
  'drizzle-zod': ^0.8.3
  'pg': ^8.20.0
  'zod': ^3.25.76
  'zod-to-json-schema': ^3.25.76

onlyBuiltDependencies:
  - esbuild

overrides:
  # drizzle-kit uses esbuild internally on an older version that's vulnerable, this overrides it
  "@esbuild-kit/esm-loader": "npm:tsx@^4.21.0"
  esbuild: "0.27.3"
